gui_apt_packages:
- mplayer
- wireshark
terminal_apt_packages:
- ant
- build-essential
- cargo
- cmake
- curl
- debhelper
- devscripts
- dos2unix
- emacs
- erlang
- erlang-doc
- freetds-bin
- freetds-dev
- git
- gpg
- gradle
- htop
- inotify-tools
- jq
- lame
- libxml2-utils
- lm-sensors
- mono-devel
- mono-xbuild
- ncurses-dev
- nmon
- p7zip-full
- pandoc
- python3
- python3-dev
- python3-setuptools
- python-dev
- ssh
- sshfs
- sysstat
- tcpdump
- texlive-full
- tig
- tmux
- tmuxp
- traceroute
- tshark
- vim
- whois
- xclip
- xvfb
- zsh
apt_packages_to_purge:
- golang
- golang-go
